parroty/exvcr

lib/exvcr/util.ex

:erlang.now is deprecated in Erlang 18, and so this change its use to
:os.timestamp instead.
Unfortunately I don't think os.timestamp has the same uniqueness guarantees that erlang.now had, and it is used to generate a uniq_id, and so may not be an appropriate solution.

Replace erlang.now with os.timestamp

---

lib/exvcr/adapter/hackney/converter.ex
test/adapter_hackney_test.exs

HTTPoison (and hackney) use a request body like `{:form, [key: "value"]}` for form data. ExVCR was choking on this by calling `to_string/1` on the body, so I've added another pattern-matched function definition to the hackney converter to handle this case.

Add support for POST requests with form-encoded data in the hackney adapter

---

lib/exvcr/filter.ex
lib/exvcr/handler.ex

There are cases where the url may contain sensitive information, so I made a change to apply the filter also in the request url.
For example, in this case it is necessary to replace the project_id.
```js
[
{
"request": {
// ...
"url": "https://api.keen.io/3.0/projects/[project_id]/events/start"
},
// ...
}
]
```

[filter] Filter sensitive data in `request url`

---

lib/exvcr/adapter/hackney.ex
lib/exvcr/adapter/hackney/converter.ex
lib/exvcr/adapter/httpc.ex
lib/exvcr/adapter/ibrowse.ex
lib/exvcr/converter.ex
lib/exvcr/handler.ex
lib/exvcr/mock.ex
lib/exvcr/records.ex
test/handler_stub_mode_test.exs

The cassettes were only matching on url and method for the request. In cases were a request body was required but not provided, the request would still be matched and tests would pass. This PR validates that the request_body matches the expectation. If the request body does not match an `InvalidRequestError` is raised.

Match cassette requests on the request body

---

fixture/custom_cassettes/httpoison_get_alternate.json
lib/exvcr/handler.ex
test/adapter_hackney_test.exs

According to the [VCR docs](1) identical requests in a cassette should be replayed in sequence, this can be useful for writing tests for behaviour such as retrying after receiving a 500 response.
I don't think this is the best implementation, but it's a starting point for discussion (and allows me to start relying on this behaviour).
Also, I'm sure there must be a much nicer way to do `Enum.reverse(acc) ++ tail ++ [response]`, but I'm pretty much a complete beginner to writing Elixir.
[1]: https://relishapp.com/vcr/vcr/v/2-9-3/docs/request-matching/identical-requests-are-replayed-in-sequence

Response sequence

---

README.md

While using the library in one of my projects, I had some hard time figuring out why the regular expression string was not working. In order to avoid escaping the `/`, I was using another delimiter.
I had to dig into the source code to figure out what was going on. This PR adds some extra information about what kind of syntax is expected for the regular expression string.

Add extra info about matching the URL with a regexp

---

fixture/vcr_cassettes/example_httpc_request_4_additional_options.json
lib/exvcr/adapter/httpc.ex
test/adapter_httpc_test.exs

The body was extracted from the wrong place in `generate_keys_for_request`. By the way, I've cleaned the function up a bit.

Fix wrong request arguments handling for httpc adapter

---

lib/exvcr/adapter/hackney.ex

The warning was as follows:
lib/exvcr/adapter/hackney.ex:94: warning: the variable "body" is unsafe as it has been set in a conditional clause, as part of a case/cond/receive/if/&&/||. Please rewrite the clauses so the value is explicitly returned. For example:

Fix warning

---

lib/exvcr/config.ex
lib/exvcr/json.ex

* when user of the app calls `cassette_library_dir/2`, that function is
actually being called twice. 1st time because of
ConfigLoader.load_defaults and 2nd time with the custom dir. Thus,
calling `File.mkdir_p` inside `cassette_library_dir/2` with a custom
dir, always created 2 dirs: the default one and the custom one
* it looks like this call isn't needed here, because `ExVCR.JSON.save/2`
creates a directory when it doesn't exist
* Use `File.mkdir_p!` since we don't do explicit error handling

Fix configuring cassette_library_dir

---

lib/exvcr/adapter/ibrowse.ex

Before storing a response in the cache, `convert_to_string` is called which, for ibrowse, converts the status code from a char list to an integer. This is usually fine, unless you're making the same api request when recording a single cassette. On the second request, the response is grabbed from the cache and passed to ibrowse to return to the user. But, since the stored response has been converted from it's original tuple of char lists, ibrowse returns a response HTTPotion is not expecting, an integer status_code instead of a char list. This might be better solved by changing the representation of the response in the cache, but this fixed the immediate bug we hit in our tests.

Fix cached status code for ibrowse

---

fixture/vcr_cassettes/different_headers_off.json
fixture/vcr_cassettes/different_headers_on.json
lib/exvcr/adapter/hackney.ex
lib/exvcr/adapter/httpc.ex
lib/exvcr/adapter/ibrowse.ex
lib/exvcr/handler.ex
lib/exvcr/util.ex
test/handler_options_test.exs

A lot of apps authenticate via a token in the headers. We ran into an issue where exvcr would not allow us to make a request to the same endpoint as a different user and verify different results. This adds the support to allow matching by headers.
I'm happy to take any feedback. Please let me know if there is anything missing.

Allow matching requests by headers

---

lib/exvcr/filter.ex
test/filter_test.exs

I was looking at a package that uses ExVCR and noticed that the cassettes were not filtering the headers that were specified in the config. It turns out to be a case sensitivity issue. I think it doesn't show up in the ExVCR specs because the test server, HttpServer, seems to use all lowercase headers.
I also noticed there is not a unit test file for `ExVCR.Filter`. I added one, but only added tests for the `remove_blacklisted_headers` method for now.
P.S. This is my first Elixir PR, apologies if I'm not following proper conventions yet. 😊 I'll be happy to fix mistakes.

Ensure blacklist header check is case insensitive.

---

test/filter_test.exs

I added tests for the other public methods in `ExVCR.Filter`. These get tested again in the `recorder_*` tests, so maybe these are redundant. Or perhaps the tests in the recorder tests can be simplified because the core functionality is proven here. I'm not sure which is best.
I also refactored the test for `remove_blacklisted_headers`, as it seems like tests tend to group related asserts in one test rather than have separate ones.
I am still new to Elixir...I'm happy to make any fixes or to be told these tests are overkill. 😄

Filter Tests

---

lib/exvcr/handler.ex
test/adapter_ibrowse_test.exs

When investigating `RequestNotMatchError` exceptions, it can be hard to see where the problem is. The best approach _seems_ to be to move your cassettes to one side, re-run the test, then diff the new and old cassettes to see where the change it.
This is a pretty slow and laborious developer experience.
Include some basic information about the request which didn't match anything in the active cassette, to help the developer zero in on where the problem is.
Example message:
```
Request did not match with any one in the current cassette: fixture/vcr_cassettes/example_ibrowse_different.json.
Delete the current cassette with [mix vcr.delete] and re-record.
Request: ['http://example.com/different_from_original', [], :get]
```
If there's a better way to format the request in a human-friendly …

Include request info when NotMatchError occurs

---

fixture/vcr_cassettes/hackney_with_body.json
lib/exvcr/adapter.ex
lib/exvcr/adapter/hackney.ex
lib/exvcr/adapter/hackney/converter.ex
lib/exvcr/handler.ex
test/adapter_hackney_test.exs
test/recorder_hackney_test.exs

There were a couple issues:
- `sanitize_options` assumed that every value in `options` is
a tuple, but hackney supports some boolean options being
specified just as atoms:
https://github.com/benoitc/hackney/blob/1.6.3/src/hackney.erl#L1016-L1019
- When `:with_body` is provided, the return value from
`:hackney.request/5` has the body as the last element
in the tuple instead of the client.
These two issues affect both recording and replaying of cassettes, so
I added tests for both sides of it.

Fix hackney adapter to work with `:with_body` option.

---

.travis.yml
lib/exvcr/converter.ex

Elixir 1.4 deprecates the use of `defoverridable` with private functions and recommends using `Enum.uniq_by/2` instead of `Enum.uniq/2`.
This was adding a fair bit of noise to my test suite after upgrading, so assuming this is merged it might be good to get a new version released so others don't run into it.

Remove elixir 1.4 deprecations

---

mix.exs

Not all applications you depend on were specified and
applications that you require only in dev/test were listed.
I have not verified this is correct but it is a push in the
right direction. Please read this blog post for more information:
http://blog.plataformatec.com.br/2016/07/understanding-deps-and-applications-in-your-mixfile/
This may break the test suite but you can fix it by calling
`Application.ensure_all_started(:http_server)` in your
test_helper.exs.

Tidy up the applications list

---

lib/exvcr/config_loader.ex
lib/exvcr/setting.ex
lib/exvcr/task/util.ex
lib/mix/tasks.ex

When running the `Mix` tasks defined in this project, they would only use the hard-coded default paths for recorded and custom cassettes and not consider the config. This demonstrates different configuration behavior between managing cassette data when running tests and managing cassette data from mix tasks.
These changes now look at the `Mix.Config` related to `exvcr` and use those directories if they are not specified on the CLI and then fallback to the defaults if a custom config is not used in both the context of the project's `Mix` tasks and running tests.
Related to Issue https://github.com/parroty/exvcr/issues/82

Load configuration for cassette paths for mix tasks

---

fixture/vcr_cassettes/hackney_head.json
fixture/vcr_cassettes/httpoison_head.json
lib/exvcr/adapter/hackney.ex
lib/exvcr/adapter/hackney/converter.ex
lib/exvcr/json.ex
test/adapter_hackney_test.exs

This allows use of HEAD requests from hackney or HTTPoison, addressing #83, which I also have been experiencing.
(HEAD requests have no body, so I had to add some pattern matching to handle circumstances when the body was `nil`.)
Please let me know what you think!

Add support for HEAD request in hackney

---

lib/exvcr/adapter/hackney/converter.ex
lib/exvcr/adapter/ibrowse/converter.ex
lib/exvcr/config.ex
lib/exvcr/config_loader.ex
lib/exvcr/converter.ex
lib/exvcr/filter.ex
test/recorder_hackney_test.exs
test/recorder_ibrowse_test.exs

Hi,
I was using exvcr for a project that needs to connect to an external API using basic_auth to get a cookie (and then use that cookie for all the consequent requests).
Using HTTPoison and hackney, I have to pass the basic_auth parameters trough the options and I discovered it was impossible to filter those data.
Hope this PR is useful for others too :)
Emanuel

Adding filter_request_options to filter sensitive data in request options

---

README.md
config/config.exs

Setting `filter_request_headers` on `config.exs` is currently working and is a nicer alternative to explicitly setting `ExVCR.Config.filter_request_headers("X-My-Secret-Token")` in the test files.
This PR adds the option to the default `config.exs` and to the README file.

Adds filter_request_headers to default parameters

---

lib/exvcr/mock.ex
test/handler_options_test.exs

In master, any failing spec raises ExUnit.AssertionError.  So any exvcr test that fails will skip clearing the mock, which then breaks all subsequent tests because they're running with another test's cassette.
I just moved your clear code into the after block to resolve, and added a test to verify.

!! Ensure clear_mock runs after each test

---

lib/exvcr/adapter/httpc/converter.ex
lib/exvcr/adapter/ibrowse.ex
lib/exvcr/adapter/ibrowse/converter.ex

[`Kernel.to_char_list` and `Integer.to_char_list` have been deprecated](https://github.com/elixir-lang/elixir/blob/0b0ab9f8ef420ea07878e3156386ddad10bb3ea8/lib/elixir/src/elixir_dispatch.erl#L382-L385) in favor of the versions with one less underscore:
See elixir-lang/elixir#4909.
This change will silence the warnings when compiling the package.

Address deprecations

---

fixture/vcr_cassettes/hackney_get_gzipped.json
lib/exvcr/json.ex
lib/exvcr/records.ex
mix.exs
mix.lock

Hi!
I ran into some issues when using VCR to record interactions with a MessagePack based backend since JSON can only encode binary data.
I rewrote the saving and loading parts to base64-encode the data, if it is deemed to be binary (i.e isn't a valid string).
Since the gzip handling is a subset of binary data, I got rid of the special casing for gzipped data as well. The downside of this is that old cassettes containing gzipped data will need to be re-recorded (we could of course keep the special casing of gzipped data) and gzipped endpoints won't be easily inspectable via the json cassettes.
I think that's a fair tradeoff in order to get the recordings as close as possible to the actual API.

Support binary responses

---

config/config.exs
lib/exvcr/setting.ex
test/enable_global_settings_test.exs

We need to mock the responses of HTTPoison calls that get triggered through a Task, and prior versions of ExVCR would not conflict with it because there was a common global ETS table name. While fixing the async behaviour, ExVCR also made it impossible to have any custom settings apply to tasks spawned outside of test code.
It broke `setup_all` and that behaviour is documented and is fixable, but I cannot think of a fix for this particular scenario other than going back to a global name for when we want this behaviour. This PR adds back using a global name as an option.
If you think that a better way to do this exists, please let me know.

Add a config key to allow a global ets settings table

---

lib/exvcr/adapter/hackney.ex
lib/exvcr/adapter/hackney/converter.ex

Fixes #144.
When calling either of
```elixir
:hackney.head(url)
:hackney.request(:head, url)
```
no request is matched in the `target_methods/1` call, due to the fact
that in Hackney `head` function calls in hackney don't call the `body`
function.
As a result, when making `:hackney.head/1` calls, the request hits
the destination instead of being captured.
I'm not sure if this is the best option to do so, but adding defaults seemed a sensible option.

Enforce match on :hackney.request/1, /2, /3 and /4

---

README.md
fixture/vcr_cassettes/user_defined_matchers_matching.json
fixture/vcr_cassettes/user_defined_matchers_not_matching.json
lib/exvcr/handler.ex
test/handler_options_test.exs

Hello!
This changeset adds the ability to specify any function (or set of functions)
that provide custom matching behaviour by using a new `custom_matchers` option.
As demonstrated in the example provided in the README.md and tests, this should allow to resolve issues like #134 where more specific matching logic is for whatever reason required.
This also opens the possibility of a bigger refactor, where even the "default" matchers (url, method, headers, body etc) are simply functions that are applied in the same way, and users can decide which ones to use or not (removing the need for the `match_requests_on` option).

Add support for custom matcher functions

---

lib/exvcr/handler.ex
test/recorder_hackney_test.exs
test/recorder_httpc_test.exs
test/recorder_ibrowse_test.exs

When you configure ExVCR with `filter_sensitive_data` and/or `filter_request_headers` any sensitive information is removed from request headers when stored on disk as a cassette. If you attempt to use the stored cassette, and specify `match_requests_on: [:headers]`, it won't match because the header values have been filtered and won't be the same as the unfiltered raw request headers.
This pull request applies sensitive data filtering to the request headers before comparing with recorded cassette for equality. I've included tests for each of the three adapters to verify the change.

Filter request headers before attempting to match with cassette

---

lib/mix/tasks.ex

I'm new to Elixir but fluent in Ruby/VCR. I just [implemented exvcr on a small Elixir project](https://github.com/javierjulio/binlist-elixir/) where I ran into this and thought I could take a shot at resolving it.
When running either the entry task `mix vcr` or the `mix vcr.check` task, it shows the same warning message below, but will just have a different stacktrace:
```
> mix vcr
warning: not passing the :switches or :strict option to OptionParser is deprecated
(elixir) lib/option_parser.ex:607: OptionParser.build_config/1
(elixir) lib/option_parser.ex:231: OptionParser.parse/2
lib/mix/tasks.ex:17: Mix.Tasks.Vcr.run/1
(mix) lib/mix/task.ex:331: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```
These warnings occurred on Elixir v1.9 but I'm not sure what other versions …

Fix warnings from OptionParser in exvcr mix tasks

---

config/config.exs
lib/exvcr/config.ex
lib/exvcr/config_loader.ex
lib/exvcr/handler.ex
test/strict_mode_test.exs

This change adds a new option called strict_mode. When turned on, if a matching cassette cannot be found, an error will be thrown.
- In a large codebase (e.g. has hundreds of tests) it is hard to validate if every HTTP call has a cassette defined for it. With strict_mode turned, an HTTP call without a cassette will cause a test to fail, making it easy to identify which calls are missing cassettes.
- Some HTTP calls are destructive or mutate data and should never be called while running tests. Strict_mode enables ExVCR to be used for these HTTP calls without the risk of accidentally making an actual HTTP call
In practice there's a reasonable amount of code out in the wild that will handle any exception raised in order to give a reasonable default error message to an end user/consumer. For …

Add strict_mode option to ensure HTTP calls DO NOT get made

---

README.md
fixture/vcr_cassettes/hackney_get_localhost.json
fixture/vcr_cassettes/httpc_get_localhost.json
fixture/vcr_cassettes/ibrowse_get_localhost.json
lib/exvcr/actor.ex
lib/exvcr/adapter.ex
lib/exvcr/adapter/hackney.ex
lib/exvcr/adapter/httpc.ex
lib/exvcr/adapter/ibrowse.ex
lib/exvcr/application.ex
lib/exvcr/handler.ex
lib/exvcr/iex.ex
lib/exvcr/mock.ex
lib/exvcr/recorder.ex
mix.exs
test/adapter_hackney_test.exs
test/adapter_httpc_test.exs
test/adapter_ibrowse_test.exs

Instead of call `:meck.expect` whenever we use cassette, we can implement a global mocking on application startup and global storage for the recorder.  Whenever we need to use a cassette, we can pass the recorder though `CurrentRecorder` GenServer.

Use global mock in adapters

---

.travis.yml
README.md
config/config.exs
config/test.exs
lib/exvcr/adapter.ex
lib/exvcr/adapter/hackney.ex
lib/exvcr/adapter/httpc.ex
lib/exvcr/adapter/ibrowse.ex
lib/exvcr/application.ex
lib/exvcr/mock.ex
lib/exvcr/recorder.ex

Even though all tests passed and the global mock was tested with an external application,
it was pretty optimistic to enabled that by default.
This commit changes default behavior that mocks every cassette and adds an ability to enable
the experimental feature. To do so, extend your `test.exs`:
```elixir
config :exvcr, [
global_mock: true
]
```
In Travis CI we run the same test for both default behavior and global
mock.

Make global mock experimental feature and disable it by default

---

README.md
mix.exs

This PR tweaks the HTML doc generation which includes:                                                        
- Add Changelog to both module info page and HTML doc.                                                                                     
- Set README as default HTML doc page.                                                               
-  Code example indentation.                                                            
- Fix badges inconsistent size.
- Use common source url in module config.

Misc HTML doc generation changes

---

lib/exvcr/actor.ex
lib/exvcr/mock.ex
test/adapter_hackney_test.exs
test/adapter_httpc_test.exs
test/adapter_ibrowse_test.exs

The initial state should be `nil` to properly bypass mock when no cassette is used.
See https://github.com/parroty/exvcr/issues/159#issuecomment-726233421

Fix CurrentRecorder initial state

---

test/adapter_httpc_test.exs
test/adapter_ibrowse_test.exs
test/recorder_httpc_test.exs

```elixir
1) test remove blacklisted headers (ExVCR.RecorderHttpcTest)
test/recorder_httpc_test.exs:116
Assertion with == failed
code:  assert headers == [{'server', 'Cowboy'}, {'content-length', '13'}]
left:  [{'content-length', '13'}, {'server', 'Cowboy'}]
right: [{'server', 'Cowboy'}, {'content-length', '13'}]
stacktrace:
test/recorder_httpc_test.exs:120: (test)
```
```elixir
Generated exvcr app
warning: Kernel.to_char_list/1 is deprecated, use Kernel.to_charlist/1 instead
test/adapter_httpc_test.exs:21: ExVCR.Adapter.HttpcTest."test passthrough works when CurrentRecorder has an initial state"/1
warning: Kernel.to_char_list/1 is deprecated, use Kernel.to_charlist/1 instead
test/adapter_httpc_test.exs:28: ExVCR.Adapter.HttpcTest."test passthrough works after cassette has been used"/1 …
```

Fix test errors and warnings

---

lib/exvcr/adapter/hackney/converter.ex
test/recorder_hackney_test.exs

When setting ssl options in hackney, we need to get the existing ssl options and merge them with any needed additions. The problem is that the existing ssl options contain function names, which the hackney converter `sanitize_options` function does not properly handle, resulting in an ArgumentError.
Updated the hackney converter `sanitize_options` function.

Fix sanitize options function in hackney adapter converter

---

mix.lock

Running tests on Elixir 1.12.2 / OTP 24.0.3 produces the following error on 8 of the tests:
```
** (UndefinedFunctionError) function :erlang.get_stacktrace/0 is undefined or private, use the new try/catch syntax for retrieving the stack backtrace
```
Updating the `meck` dependency fixes the issue.

Update meck to fix failing tests

---

lib/exvcr/adapter/finch.ex

If there is no Finch dependency error, the compile for the project using ExVCR fails.
Thanks to @ruslandoga for noticing and giving a suggestion for the fix!
As suggested, we define the adapter module conditionally and raise if the adapter is used without a Finch dependency loaded.
Ideally we should also figure out a way to test this case, but for now let's just release a new version to minimize any inconvenience - sorry for this oversight on my part!

Define Finch adapter conditionally to fix compile error

---

README.md
lib/exvcr/setting.ex
test/setting_test.exs

This is a pretty useful feature yet somehow it's hidden within the codebase. Let's document it. :)

Better document the ignore_urls setting

---

lib/exvcr/handler.ex

When using additional match criteria via the `:match_requests_on` option this `InvalidRequestError` message will now report the components that were matched against. The aim is to improve the developer experience. 🧑‍💻
It allows the developer to immediately see the data in the request's query, request body or headers that ExVcr is using to match.

Add additional information to the InvalidRequestError message.

---

lib/exvcr/config.ex
lib/exvcr/mock.ex

Warnings were being issued regarding duplicate documentation
declarations. Here's an example:
```
warning: redefining @doc attribute previously set at line 27.
Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head (the function signature not followed by any do-block). For example:
@doc """
new docs
"""
def use_cassette(...)
lib/exvcr/mock.ex:48: ExVCR.Mock.use_cassette/3
```
This change resolves these warnings by merging documentation and adding
examples that were already available in the README file.

Resolve Duplicate Docs Warnings

---

mix.exs

Hey there! 🖖 
This PR simply loosens the `httpoison ~> 1.0` constraint. 
The breaking changes from [httpoison](https://hex.pm/packages/httpoison) 1.8.2 to 2.0 are related to SSL options - which are not used by exvcr. Therefore, loosening the constraint shouldn't have any collateral effect on exvcr.
For more details about the breaking changes, see [httpoison 2.0.0 release](https://github.com/edgurgel/httpoison/releases/tag/v2.0.0). 
Closes #195

Adds httpoison ~> 2.0 support

---

test/recorder_finch_test.exs

Aditional fix for avoiding intermittent failure in #197 
```
Check failure on line 44 in test/recorder_finch_test.exs
GitHub Actions
/ Run Tests (21, 1.10, true)
test forcefully getting response from server with error (ExVCR.RecorderFinchTest)
```

Fix name conflict for finch test case

---

lib/exvcr/adapter/finch/converter.ex

This PR wraps `lib/exvcr/adapter/finch/converter.ex` in a `if Code.ensure_loaded?(Finch) do` block.
Closes #204

Fix compilation in project lacking Finch

---

config/config.exs
config/test.exs
lib/exvcr/adapter/hackney/converter.ex
mix.exs

This PR fixes all warnings emitted by Elixir 1.14.5 (Erlang 25). Probably should be squashed during merge.
```
warning: use Mix.Config is deprecated. Use the Config module instead
config/config.exs:1
```
```
warning: :hackney_request.encode_form/1 defined in application :hackney is used by the current application but the current application does not depend on :hackney. To fix this, you must do one of:
1. If :hackney is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs
2. If :hackney is a dependency, make sure it is listed under "def deps" in your mix.exs
3. In case you don't want to add a requirement to :hackney, you may optionally skip this warning by adding [xref: [exclude: [:hackney_request]]] to your "def project" in mix.exs …
```

Fix Elixir 1.14 warnings

---

lib/exvcr/filter.ex
test/filter_test.exs

This PR allows for values other than strings to be passed in to `Filter.filter_sensitive_data/1`
Closes: https://github.com/parroty/exvcr/issues/208

fix: Allow numeric options

---

fixture/custom_cassettes/response_mocking_with_param.json
fixture/vcr_cassettes/different_query_params_on.json
lib/exvcr/handler.ex
test/handler_custom_mode_test.exs
test/handler_options_test.exs
test/handler_stub_mode_test.exs

Before these changes, if the request body or URL contained a list of params that were in a different order than the params in the cassette, the request would fail to match the cassette.
As of OTP 26, map key order is not guaranteed, so request bodies and URL params that are created using maps can fail to match since the order of their keys is not idempotent.
These changes convert the request body and URL params to a sorted list before comparing it to the request body and URL in the cassette. This ensures cassettes will be matched as long as their request bodies and URL params contain the same set of key-value pairs as the incoming request.

Normalizes request body and URL by parsing params to a list and sorting

---

README.md
lib/exvcr/mock.ex
test/adapter_finch_test.exs
test/adapter_ibrowse_test.exs

Hello there! 👋
Since we support multiple requests when using fixtures I thought it would be nice to support multiple requests also when using the `:stub` option.
This feature is quite useful in scenarios in which we need to create stubs manually or dynamically.
Usage:
```elixir
stubs = [
[url: "http://example.com/1", body: "Stub Response 1", status_code: 200],
[url: "http://example.com/2", body: "Stub Response 2", status_code: 404]
]
use_cassette :stub, stubs do
{:ok, response} = Finch.build(:get, "http://example.com/1") |> Finch.request(ExVCRFinch)
assert response.status == 200
assert response.body =~ ~r/Stub Response 1/
{:ok, response} = Finch.build(:get, "http://example.com/2") |> Finch.request(ExVCRFinch)
assert response.status == 404
assert response.body =~ ~r/Stub Response 2/
end …
```

Support for Multiple Stub Requests

---

README.md

Hi thanks a lot for your work on exvcr! I was recently playing a bit with it and found some issues on the documentation, so I thought a PR would help you.
The readme has some links that are not rendering well on https://hexdocs.pm/exvcr, in addition some of the code examples use `Elixir` as language name, so the highlighting doesn't work.
I've changed the links so that they render well on hexdocs and rexpect the existing `target="_blank"`.
I've also changed the language in the codeblocks so that it is correctly highlighted on both hexdocs and GitHub.
I was only able to get the docs rendered on Elixir 1.14. I tried 1.15 and 1.16 too, but they didn't work and I was always getting an error like this:
```
❯ mix docs               
Generated exvcr app
13:46:12.122 [notice] Application makeup …
```

fix: link rendering and code highlights

---

.github/workflows/tests.yml

This pull request includes changes to the `.github/workflows/tests.yml` file to update the test environment and the actions used in the GitHub workflow. The most important changes are updating the OTP and Elixir versions used in the test matrix, updating the versions of the GitHub actions used, and replacing the `retry` action with a newer version.
Test environment updates:
* OTP version '21' was removed from the test matrix, and versions '24' with Elixir '1.12' were added. This change updates the versions of OTP and Elixir that the tests are run against, ensuring compatibility with newer versions of these tools.
GitHub actions updates:
* The `actions/checkout` and `actions/cache` actions were updated to version 4. These updates may include bug fixes, new features, or performance …

Fix versions in actions workflow

---

README.md

Today I've spent around half an hour trying to make negative examples from this doc to work. 😄 
Therefore, I'd like to save some time to the next person who's going to use this doc by better clarifying that it should not work in the snippet itself.

Clarify README part about regexp matches in stub cassetes

---

README.md

Deleted kmardown syntaxys as it breaks the [readme](https://github.com/parroty/exvcr/blob/b8a715f12d3f3d63a68ae7f8a385b2b0d3d939a2/README.md#basics) and the [doc](https://hexdocs.pm/exvcr/readme.html#basics) links in hexdoc: ![image](https://github.com/user-attachments/assets/51807f4f-4547-4820-9095-c5191dbcd551)

remove kramdown syntax from links

---

.github/workflows/tests.yml
mix.exs

This pull request includes updates to the GitHub Actions workflow configuration to enhance the testing matrix and improve error handling. The key changes are:
Workflow configuration updates:
* [`.github/workflows/tests.yml`](diffhunk://#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fL8-R37): Updated the `runs-on` environment to `ubuntu-22.04` and added the `continue-on-error` parameter to handle experimental configurations.
* [`.github/workflows/tests.yml`](diffhunk://#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fL8-R37): Introduced the `fail-fast` parameter to the strategy to stop all jobs if any job fails.
* [`.github/workflows/tests.yml`](diffhunk://#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fL8-R37): Expanded the …

Update GitHub Actions workflow to use Ubuntu 22.04 and add support for Elixir 1.16 and 1.18.0

---

mix.exs

Fixes an Elixir 1.19 deprecation: https://hexdocs.pm/elixir/main/changelog.html
`def cli` was introduced in 1.15 so it's backward compatible.

Move preferred_cli_env into def cli

---

test/adapter_finch_test.exs
test/adapter_hackney_test.exs
test/adapter_httpc_test.exs
test/adapter_ibrowse_test.exs
test/handler_stub_mode_test.exs
test/iex_test.exs
test/recorder_httpc_test.exs

Elixir 1.18 has introduced new `mix format --migrate` which allows to fix multiple warnings/deprecations at once.
This should simplify running tests for the library, given that running tests will no longer produce multiple screens of warnings.

Fix charlist warnings in tests
